#!/bin/bash

info "Installing Ubuntu OSX Theme. Tested in Ubuntu 21.04 and 21.10";

DIRECTORY="$(pwd)";
BACKGROUNDS_PATH="$HOME/Backgrounds/ubuntu.jpg";

#Downloading basic tools
sudo apt-get install -y vim;
sudo apt-get install -y git;

#Setting xbash tools
mkdir "$DIRECTORY/vendor";
cd vendor;
git clone "https://github.com/codeflow/xbash.git";

#Importing xbash tools
source "$DIRECTORY/vendor/xbash/styles/colors.xb";
source "$DIRECTORY/vendor/xbash/styles/styles.xb";
source "$DIRECTORY/vendor/xbash/utils/logger.xb";

cd "$DIRECTORY";

#Setting OSX Theme
if [[ "$1" == "-b" || "$1" == "--use-backup" ]]; then
	cp -R backup/osx-theme .;
else
	git clone "https://github.com/vinceliuice/WhiteSur-gtk-theme.git";
	mv WhiteSur-gtk-theme/ osx-theme/;
fi

mkdir -p "$HOME/Backgrounds";

cp "$DIRECTORY/images/ubuntu.jpg" "$HOME/Backgrounds";
cp "$DIRECTORY/images/ubuntu.jpg" "$DIRECTORY/osx-theme";

cd osx-theme;

./install.sh -c dark -c light -t all -i ubuntu;
./tweaks.sh -f monterey
sudo ./tweaks.sh -g -n -b "ubuntu.jpg" -c dark

#Extensions, session and tweaks
sudo apt-get install -y gnome-tweaks;
sudo apt-get install -y gnome-shell-extensions;
sudo apt-get install -y gnome-shell-extension-prefs gnome-tweaks;
sudo apt-get install -y gnome-session;

gnome-extensions enable user-theme@gnome-shell-extensions.gcampax.github.com;

#Icons settings
sudo mv "$DIRECTORY/icons/Cupertino-Monterey" "/usr/share/icons";
sudo rm -rf "/usr/share/icons/Adwaita";
sudo mv "$DIRECTORY/icons/Adwaita" "/usr/share/icons";

sudo apt install -y gnome-shell-extension-autohidetopbar;

#Interface settings
gsettings set org.gnome.shell.extensions.dash-to-dock autohide false;
gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false;
gsettings set org.gnome.shell.extensions.dash-to-dock intellihide false;
gsettings set org.gnome.desktop.interface icon-theme 'Cupertino-Monterey';
gsettings set org.gnome.desktop.interface gtk-theme 'WhiteSur-dark-solid';
gsettings set org.gnome.shell.extensions.user-theme name 'WhiteSur-dark-solid';
gsettings set org.gnome.desktop.background picture-uri "$BACKGROUNDS_PATH";
gsettings set org.gnome.shell.extensions.dash-to-dock dock-position 'LEFT';
gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 26;
gsettings set org.gnome.shell enabled-extensions "['apps-menu@gnome-shell-extensions.gcampax.github.com', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'places-menu@gnome-shell-extensions.gcampax.github.com', 'native-window-placement@gnome-shell-extensions.gcampax.github.com', 'desktop-icons@csoriano', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'windowsNavigator@gnome-shell-extensions.gcampax.github.com', 'ubuntu-appindicators@ubuntu.com', 'hidetopbar@mathieu.bidon.ca']";

mkdir $HOME/.local/share/fonts;
cp "$DIRECTORY"/fonts/SF* $HOME/.local/share/fonts;
fc-cache -f -v;

gsettings set org.gnome.desktop.interface document-font-name 'SF Pro Display 10';
gsettings set org.gnome.desktop.interface font-name 'SF Pro Display 10';
gsettings set org.gnome.desktop.wm.preferences titlebar-font 'SF Pro Display 10';
gsettings set org.gnome.desktop.interface monospace-font-name 'Monospace 11';
gsettings set org.gnome.desktop.interface font-hinting 'full';
gsettings set org.gnome.desktop.interface font-antialiasing 'rgba';
gsettings set org.gnome.desktop.interface scaling-factor 'uint32 0';
gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,close';
gsettings set org.gnome.desktop.wm.preferences action-middle-click-titlebar 'minimize';
gsettings set org.gnome.mutter attach-modal-dialogs 'false';
gsettings set org.gnome.desktop.interface clock-show-weekday 'true';

#Powerline settings
sudo apt-get update;
sudo apt install -y python3-pip;
pip3 install --user powerline-status;

cat "$DIRECTORY/bash/powerline-settings" >> "$HOME/.bash_profile";
echo " " >> $HOME/.bashrc;
echo "#Powerline bash settings" >> $HOME/.bashrc;
echo "source $HOME/.bash_profile" >> $HOME/.bashrc;
source $HOME/.bash_profile;

cp "$DIRECTORY/bash/powerline-gitstatus.json" "$HOME/.local/lib/python3.9/site-packages/powerline/config_files/colorschemes/default.json";
cp "$DIRECTORY/bash/powerline-shell.json" "$HOME/.local/lib/python3.9/site-packages/powerline/config_files/themes/shell/default.json";

"$DIRECTORY/bash/fonts/install.sh";
cp "$DIRECTORY/bash/fonts/'Menlo for Powerline.ttf'" "$HOME/.local/share/fonts/'Menlo for Powerline.ttf'";
sudo fc-cache -vf $HOME/.local/share/fonts;

#Terminal powerline font settings
GNOME_TERMINAL_PROFILE=`gsettings get org.gnome.Terminal.ProfilesList default | awk -F \' '{print $2}'`;
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$GNOME_TERMINAL_PROFILE/ font 'Meslo LG S DZ for Powerline Regular 9';
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$GNOME_TERMINAL_PROFILE/ use-system-font false;
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$GNOME_TERMINAL_PROFILE/ background-color '#000000';
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$GNOME_TERMINAL_PROFILE/ foreground-color '#FFFFFF';
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$GNOME_TERMINAL_PROFILE/ use-theme-colors false;

#Gedit settings
gsettings set org.gnome.gedit.preferences.editor wrap-mode 'word';
gsettings set org.gnome.gedit.preferences.editor auto-save-interval 'uint32 2';
gsettings set org.gnome.gedit.preferences.editor wrap-last-split-mode 'word';
gsettings set org.gnome.gedit.preferences.editor use-default-font 'true';
gsettings set org.gnome.gedit.preferences.editor tabs-size 'uint32 3';
gsettings set org.gnome.gedit.preferences.editor auto-save 'true';
gsettings set org.gnome.gedit.preferences.editor background-pattern 'grid';
gsettings set org.gnome.gedit.preferences.editor smart-home-end 'after';
gsettings set org.gnome.gedit.preferences.editor search-highlighting 'true';
gsettings set org.gnome.gedit.preferences.editor scheme 'Yaru-dark';
gsettings set org.gnome.gedit.preferences.editor editor-font 'Monospace 12';
gsettings set org.gnome.gedit.preferences.editor bracket-matching 'true';
gsettings set org.gnome.gedit.preferences.editor syntax-highlighting 'true';
gsettings set org.gnome.gedit.preferences.editor display-right-margin 'true';
gsettings set org.gnome.gedit.preferences.editor auto-indent 'true';
gsettings set org.gnome.gedit.preferences.editor max-undo-actions '2000';
gsettings set org.gnome.gedit.preferences.editor restore-cursor-position 'true';
gsettings set org.gnome.gedit.preferences.editor highlight-current-line 'true';
gsettings set org.gnome.gedit.preferences.editor display-line-numbers 'true';
gsettings set org.gnome.gedit.preferences.editor insert-spaces 'false';
gsettings set org.gnome.gedit.preferences.editor display-overview-map 'true';
gsettings set org.gnome.gedit.preferences.editor ensure-trailing-newline 'true';
gsettings set org.gnome.gedit.preferences.editor right-margin-position 'uint32 80';
gsettings set org.gnome.gedit.preferences.editor create-backup-copy 'false';

#Powerline vimrc settings
echo "set rtp+=$HOME/.local/lib/python3.9/site-packages/powerline/bindings/vim/" >> $HOME/.vimrc;
echo "set laststatus=2" >> $HOME/.vimrc;
echo "set number" >> $HOME/.vimrc;
echo "syntax on" >> $HOME/.vimrc;
echo "set formatoptions=tcqrn1" >> $HOME/.vimrc;
echo "set tabstop=2" >> $HOME/.vimrc;
echo "set shiftwidth=2" >> $HOME/.vimrc;
echo "set softtabstop=2" >> $HOME/.vimrc;
echo "set expandtab" >> $HOME/.vimrc;
echo "set noshiftround" >> $HOME/.vimrc;

#Gnome session settings
sudo chown $USER:$USER /var/lib/AccountsService/users;
sudo chown $USER:$USER "/var/lib/AccountsService/users/$USER";
echo "XSession=gnome" >> "/var/lib/AccountsService/users/$USER";
sudo chown root:root /var/lib/AccountsService/users;
sudo chown root:root "/var/lib/AccountsService/users/$USER";

#Reboot
sudo shutdown -r now;
